global:
 urls:
   ipamApi: "https://ipam-api.vitistack.io/v2"
 controller:
   repository: "ncr.sky.nhn.no/ghcr/vitistack/ipam-operator"
   tag: "0.0.1-rc31"
 caBundle:
   crt: |
      -----BEGIN CERTIFICATE-----
      MIIFXjCCA0agAwIBAgIQMdRMSRPUkopCm8J2PI17vTANBgkqhkiG9w0BAQsFADBJ
      MQswCQYDVQQGEwJOTzEbMBkGA1UEChMSTm9yc2sgSGVsc2VuZXR0IFNGMR0wGwYD
      VQQDExROSE4gSW50ZXJuYWwgUm9vdCBDQTAeFw0xNzAxMTkxMjE3NDZaFw0zNzAx
      MTkxMjI3NDVaMEkxCzAJBgNVBAYTAk5PMRswGQYDVQQKExJOb3JzayBIZWxzZW5l
      dHQgU0YxHTAbBgNVBAMTFE5ITiBJbnRlcm5hbCBSb290IENBMIICIjANBgkqhkiG
      9w0BAQEFAAOCAg8AMIICCgKCAgEA238+eskVvFTUHaMXgDzzE9F6RgVdC20rQu85
      OuLa5lmO3Fh7hgHYVTzWik3NzAQHhO2akhoIZhObFMa8gSDnBkAKLYhK1begeTAh
      k3g39EVImsBXZCEW6RMZQnw2gv6lzXN7edKbsEEPW9x+YGLsoAkXCAHfHI2ZoOo+
      oiZnLdGovO4+y6CvjUGJ9L5pnZKvVY4p2UcoAtG4lGIQKLE7GU0lSp7nxoWS0v/l
      SBrNz84F372GCsS7OAcyX1SyV8kRI5XwGRbKWm3IFsnXeGlAjKgTYLJfnTmRFBVI
      9ciH7JvRcgXEvSBPGWmZ1OUrXyZMMY6mOjMHz3bp8PmAWplbkBea8saYQvbjpt47
      XUL6GVmGcR2cSCLhtEde212yM3RDUGCfO6kjerB2IT2nmQo6Nj26FXQxZyBGNHTV
      v2+C8eid8jfEP8mRhnyLBnf92sw2FYLAUxlmw8zi4RyTtMUSEX3PVTFQAgeMr2zZ
      PbudAZ27Dq0eGUUl1lzjayZglzzCGHz13hOuQgzMDZMrztBgblhZYVMW9nglxYd8
      IdGlgzw/eruCQ+TZAN8xV8nFT2Edf+GHB6W1j2kYWMVYizIFuv3s8A+lA8omYeH9
      /LdFKWa8ZxsMRpkVmuatHP0hXtNGOiZ3MXKxfxC8S9ltHlaRc07xDUyjqt118wT/
      icH42vkCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8w
      HQYDVR0OBBYEFLfegx3OGCHyCvTfp1blsXciOhJ+MA0GCSqGSIb3DQEBCwUAA4IC
      AQBsr1YPmf1NRwYm44fS0jjiuevqaGXkFTIm4s3XOU4Fd1PuJqNsG+FL1HVhu/Dw
      jsj3WUebvFLla3wHvkV0fEJSAK0zdszqqi7EXhBJByGpepu/oip2giuEVmIhH5N5
      IrylwDZ6Vpdilx0uA6pAP2l9/C9cRHop1+/Ny8EPJZNhh5pfyjSWX027MTJFpH0x
      evQJaY1e2WOEERzPpK9GuT+ctHOhoir+1XsbUrnXfprNVEpgVieuVXhRrDxDxKCS
      yXEYx7KReYh3PITC88480FaRkoGhaFJfOs237I2QJrA8uL0E5dcT95/wLWmX3fFi
      lT8dKKw2flyByP2m597MEsPZAuQI1Ov04xIVd/rjzHoFhCFbbTiQ6BbchJUtAXNm
      nBm5loaz97FID9BedSk8deV8cPe+hSODwE+YJXrqHh7FrTpJOt4wC+Ct+rMB6ePw
      K3fN6sBMWImR+9QElCB5wqPc4hGqAaclBFbdEiAS0MMXZAnsUDDck6wACsP+JEOJ
      pXdMvR+5Nsk634d6i7+CcsuUWEIQrg6q0Csh+C4g6JEK0CPLqmqgZWyRDO0SV2Tu
      FWOi47Dpnk+pvx4XFEZGLe27MVIvmzGtPL7dabdV7jLh3lgCRL91+Y9/XC4Cbbob
      Ro/BdJyio0/ihsEG4Ivw1aZzYR9IvIhxiXSGvPKVmc+bDg==
      -----END CERTIFICATE-----